//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONTAS
    {
        public int ID_CONTA { get; set; }
        public string NM_CONTA { get; set; }
        public Nullable<double> SALDO_CONTA { get; set; }
    }
}
