//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_STATUS()
        {
            this.TB_TRANSACOES = new HashSet<TB_TRANSACOES>();
        }
    
        public int ID_STATUS { get; set; }
        public string NM_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TRANSACOES> TB_TRANSACOES { get; set; }
    }
}
