//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRANSACOES
    {
        public int ID_TRANSACAO { get; set; }
        public Nullable<int> IDE_CONTA_ORIGEM { get; set; }
        public Nullable<int> IDE_CONTA_DESTINO { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<int> IDE_STATUS { get; set; }
        public Nullable<System.DateTime> DATA_TRANSACAO { get; set; }
        public Nullable<System.DateTime> DATA_RESULTADO { get; set; }
    
        public virtual TB_CONTAS DESTINO { get; set; }
        public virtual TB_CONTAS ORIGEM { get; set; }
        public virtual TB_STATUS STATUS { get; set; }
    }
}
